### ISSUE TITLE
opening IDA 7.6 idb

### ISSUE THREAD

**Issue by TakahiroHaruyama** [williballenthin/python-idb#103]
Hi,

I have an UnicodeDecodeError when opening IDA 7.6 idb.
Probably the internal structure has changed?

Thanks,
Takahiro

In [3]: with idb.from_file("efi_modules/CpuDxe.efi.i64") as db:
   ...:     api = idb.IDAPython(db)
   ...:
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-f5d91a681500> in <module>
----> 1 with idb.from_file("efi_modules/CpuDxe.efi.i64") as db:
      2     api = idb.IDAPython(db)
      3

c:\python39-x64\lib\contextlib.py in __enter__(self)
    115         del self.args, self.kwds, self.func
    116         try:
--> 117             return next(self.gen)
    118         except StopIteration:
    119             raise RuntimeError("generator didn't yield") from None

c:\python39-x64\lib\site-packages\idb\__init__.py in from_file(path)
     31         buf = memview(f.read())
     32         db = idb.fileformat.IDB(buf)
---> 33         db.vsParse(buf)
     34         yield db
     35

c:\python39-x64\lib\site-packages\vstruct\__init__.py in vsParse(self, sbytes, offset, fast)
    143                 raise struct.error("Failed to parse field `{:s}.{:s}` at offset {:s}".format(
    144                     self.__class__.__name__, fname, hex(offset)))
--> 145             self._vsFireCallbacks(fname)
    146         return offset
    147

c:\python39-x64\lib\site-packages\vstruct\__init__.py in _vsFireCallbacks(self, fname)
     86         callback = getattr(self, 'pcb_%s' % fname, None)
     87         if callback != None:
---> 88             callback()
     89         cblist = self._vs_pcallbacks.get(fname)
     90         if cblist != None:

c:\python39-x64\lib\site-packages\idb\fileformat.py in pcb_header(self)
   1197             s.vsParse(section.contents)
   1198             if isinstance(s, TIL):
-> 1199                 s.inf = Root(self).idainfo
   1200             # vivisect doesn't allow you to assign vstructs to
   1201             #  attributes that are not part of the struct,

c:\python39-x64\lib\site-packages\idb\analysis.py in __getattr__(self, key)
    363                 return bytes(v)
    364             else:
--> 365                 return field.cast(bytes(v), wordsize=self.idb.wordsize)
    366
    367     def get_field_tag(self, name):

c:\python39-x64\lib\site-packages\idb\analysis.py in inner(buf, wordsize)
     94
     95     def inner(buf, wordsize=None):
---> 96         return cast(buf, V, wordsize=wordsize)
     97
     98     setattr(inner, "V", V.__name__)

c:\python39-x64\lib\site-packages\idb\analysis.py in cast(buf, V, wordsize)
     72     """
     73     v = V(wordsize=wordsize)
---> 74     v.vsParse(buf)
     75     return v
     76

c:\python39-x64\lib\site-packages\idb\analysis.py in vsParse(self, sbytes, offset, fast)
    634             self.procname = reader.str(8)
    635         elif self.version >= 700:
--> 636             self.procname = reader.str(16)
    637         import re
    638

c:\python39-x64\lib\site-packages\idb\analysis.py in str(self, size, encoding)
    425
    426     def str(self, size, encoding="utf-8"):
--> 427         return self.read(size).decode(encoding)
    428
    429     def u16(self, big=False):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 8: invalid start byte

**Comment by lazydaemon** [comment]
Same problem for me.

**Comment by TakahiroHaruyama** [comment]
Are you planning to handle this issue in the future? 
or I'll change my tool just not to use python-idb :-)

**Comment by XVilka** [comment]
Yes, we do. Could you please send a PR adding a testcase to: https://github.com/williballenthin/python-idb/tree/master/tests/data
You will need to open kernel32.dll with the following hash https://github.com/williballenthin/python-idb/tree/master/tests/data/kernel32

**Comment by USSRcoder** [comment]
Same issue again.
```
C:\Users\adm\Downloads\f4>python C:\games\IDA7.7\python-idb\scripts\dump_btree.py FO4GSNoSND.exe_deb2.i64
INFO:idb.netnode:resolved string netnode Root Node to ff00000000000002
INFO:idb.netnode:resolved string netnode Root Node to ff00000000000002
Traceback (most recent call last):
  File "C:\games\IDA7.7\python-idb\scripts\dump_btree.py", line 72, in <module>
    sys.exit(main())
  File "C:\games\IDA7.7\python-idb\scripts\dump_btree.py", line 40, in main
    with idb.from_file(args.idbpath) as db:
  File "contextlib.py", line 113, in __enter__
  File "c:\old\python38\lib\site-packages\idb\__init__.py", line 33, in from_file
    db.vsParse(buf)
  File "c:\old\python38\lib\site-packages\vstruct\__init__.py", line 145, in vsParse
    self._vsFireCallbacks(fname)
  File "c:\old\python38\lib\site-packages\vstruct\__init__.py", line 88, in _vsFireCallbacks
    callback()
  File "c:\old\python38\lib\site-packages\idb\fileformat.py", line 1199, in pcb_header
    s.inf = Root(self).idainfo
  File "c:\old\python38\lib\site-packages\idb\analysis.py", line 365, in __getattr__
    return field.cast(bytes(v), wordsize=self.idb.wordsize)
  File "c:\old\python38\lib\site-packages\idb\analysis.py", line 96, in inner
    return cast(buf, V, wordsize=wordsize)
  File "c:\old\python38\lib\site-packages\idb\analysis.py", line 74, in cast
    v.vsParse(buf)
  File "c:\old\python38\lib\site-packages\idb\analysis.py", line 636, in vsParse
    self.procname = reader.str(16)
  File "c:\old\python38\lib\site-packages\idb\analysis.py", line 427, in str
    return self.read(size).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 8: invalid start byte
```
