### ISSUE TITLE
python3  execute  run_ida_script.py error

### ISSUE THREAD

**Issue by jinyu00** [williballenthin/python-idb#42]
```
lsl@yhk-RH2485-V2:~/sec_tool/feature_learn$ python3 run_ida_script.py -q ~/python-idb/scripts/yara_fn.py   ~/python-idb/tests/data/v7.0b/x64/kernel32.i64 
Traceback (most recent call last):
  File "run_ida_script.py", line 81, in <module>
    sys.exit(main())
  File "run_ida_script.py", line 75, in main
    exec(f.read(), g)
  File "<string>", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1193, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1111, in create
  File "/usr/local/lib/python3.4/dist-packages/python_idb-0.4.0-py3.5.egg/idb/shim.py", line 27, in create_module
AttributeError: 'module' object has no attribute '_Module'


```

**Comment by williballenthin** [comment]
would you try again using commit 41fa252af0d557967ab8c0c6b48ca668d89d9bff or later? I think I've fixed the issue. please re-open this issue if you encounter any problems.

thanks for reporting this bug!
