### ISSUE TITLE
GetFunctionName can't find name for function

### ISSUE THREAD

**Issue by alexandreborges** [williballenthin/python-idb#7]
Willi,

Good morning. How are you?

Do you have any suggestion about the problem below?

```
C:\analysis>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> **import idb**
>>> **with idb.from_file('banker_trojan.idb') as db:**
...           **api = idb.IDAPython(db)**
...           **for ea in api.idautils.Functions():**
...                **print('%x: %s' % (ea, api.idc.GetFunctionName(ea)))**
...
**section class not implemented: id2**
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "C:\Python35\lib\site-packages\idb\idapython.py", line 587, in GetFunctionName
    return nn.name()
  File "C:\Python35\lib\site-packages\idb\netnode.py", line 172, in name
    cursor = self.idb.id0.find(key)
  File "C:\Python35\lib\site-packages\idb\fileformat.py", line 734, in find
    s.find(c, key)
  File "C:\Python35\lib\site-packages\idb\fileformat.py", line 333, in find
    self._find(cursor, cursor.index.root_page, key)
  File "C:\Python35\lib\site-packages\idb\fileformat.py", line 329, in _find
    self._find(cursor, next_page_number, key)
  File "C:\Python35\lib\site-packages\idb\fileformat.py", line 321, in _find
    raise KeyError(key)
**KeyError: b'.e\xf9*\x94N'**
>>>
```

Have a nice day and take care.

Alexandre.

**Comment by williballenthin** [comment]
looks like its trying to pull the name for a function, yet the data its expecting isn't there.

would you please provide a sample .idb file that i can incorporate into a unit test that demonstrates this issue? then i can triage and release a fix.

**Comment by alexandreborges** [comment]
Willi, 

Good morning. I will provide the idb sample to you by e-mail.

Thank you for the reply and take care.

Alexandre.

**Comment by williballenthin** [comment]
40b7879 adds test case demonstrating this issue using the kernel32.idb from v6.95. 104b7cb fixes issue in master.
