### ISSUE TITLE
'GeneratorContextManager' object has no attribute 'wordsize'

### ISSUE THREAD

**Issue by ming950528** [williballenthin/python-idb#74]
I'm trying to parse the i64 file located at `python-idb/tests/data/arm64/`. I run following commands:
```
import idb
db = idb.from_file('ls.i64')
api = idb.IDAPython(db)
```
But I got the following exceptions
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\idb\idapython.py", line 1959, in __init__
    self.idc = idc(db, self)
  File "C:\Python27\lib\site-packages\idb\idapython.py", line 416, in __init__
    if self.idb.wordsize == 4:
AttributeError: 'GeneratorContextManager' object has no attribute 'wordsize'
```
How am I supposed to solve it? Any reply will be appreciated!

**Comment by williballenthin** [comment]
please use `from_file` as a context manager, like so:

```
with idb.from_file(args.idbpath) as db:
    api = idb.IDAPython(db)
    ....
```

**Comment by williballenthin** [comment]
example here: https://github.com/williballenthin/python-idb/blob/master/scripts/extract_function_names.py#L44-L49

**Comment by ming950528** [comment]
Thanks!
