### ISSUE TITLE
7.5 idb, V850 architecture dump_scripts.py fails on freshly created IDB with KeyError: b'N$ scriptsnippets'

### ISSUE THREAD

**Issue by XVilka** [williballenthin/python-idb#84]
Just open [`v850_hello`](https://github.com/williballenthin/python-idb/files/4963886/v850_hello.zip) in any 7.x IDA Pro with autoanalysis, then close & save. Then try to run `dump_scripts.py` on it:
```
python-idb/scripts on  master 
[i] ℤ python3 dump_scripts.py ~/radare/test/v850/v850_hello.i64                                                                                                                                                                    12:13:15 
WARNING:idb.fileformat:section class not implemented: id2
Traceback (most recent call last):
  File "dump_scripts.py", line 67, in <module>
    sys.exit(main())
  File "dump_scripts.py", line 45, in main
    for script in idb.analysis.enumerate_script_snippets(db):
  File "/home/user/.local/lib/python3.8/site-packages/idb/analysis.py", line 1602, in enumerate_script_snippets
    scripts = ScriptSnippets(db)
  File "/home/user/.local/lib/python3.8/site-packages/idb/analysis.py", line 391, in inner
    return _Analysis(db, nodeid, fields)
  File "/home/user/.local/lib/python3.8/site-packages/idb/analysis.py", line 232, in __init__
    self.netnode = idb.netnode.Netnode(db, nodeid)
  File "/home/user/.local/lib/python3.8/site-packages/idb/netnode.py", line 209, in __init__
    cursor = self.idb.id0.find(key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 794, in find
    s.find(c, key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 389, in find
    self._find(cursor, cursor.index.root_page, key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 385, in _find
    self._find(cursor, next_page_number, key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 377, in _find
    raise KeyError(key)
KeyError: b'N$ scriptsnippets'
````

**Comment by XVilka** [comment]
It happens also on the [v7.3 kernel32.i64](https://github.com/williballenthin/python-idb/blob/master/tests/data/v7.3/x64/kernel32.i64)(It's in the `tests/data/v7.3/x64` directory of this repository) as well:
```
[i] ℤ python3 dump_scripts.py ../tests/data/v7.3/x64/kernel32.i64                                                                                                                                                                  14:37:07 
WARNING:idb.fileformat:section class not implemented: id2
Traceback (most recent call last):
  File "dump_scripts.py", line 67, in <module>
    sys.exit(main())
  File "dump_scripts.py", line 45, in main
    for script in idb.analysis.enumerate_script_snippets(db):
  File "/home/user.local/lib/python3.8/site-packages/idb/analysis.py", line 1650, in enumerate_script_snippets
    scripts = ScriptSnippets(db)
  File "/home/user/.local/lib/python3.8/site-packages/idb/analysis.py", line 403, in inner
    return _Analysis(db, nodeid, fields)
  File "/home/user/.local/lib/python3.8/site-packages/idb/analysis.py", line 244, in __init__
    self.netnode = idb.netnode.Netnode(db, nodeid)
  File "/home/user/.local/lib/python3.8/site-packages/idb/netnode.py", line 209, in __init__
    cursor = self.idb.id0.find(key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 790, in find
    s.find(c, key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 385, in find
    self._find(cursor, cursor.index.root_page, key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 381, in _find
    self._find(cursor, next_page_number, key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 381, in _find
    self._find(cursor, next_page_number, key)
  File "/home/user/.local/lib/python3.8/site-packages/idb/fileformat.py", line 373, in _find
    raise KeyError(key)
KeyError: b'N$ scriptsnippets'
```

**Comment by XVilka** [comment]
Fixed in https://github.com/williballenthin/python-idb/commit/0e2c5459b0b1245e0c1a29f009205826eead1fbf
