### ISSUE TITLE
`dump_user.py v6.8/x32/kernel32.idb` - UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1-2: invalid continuation byte

### ISSUE THREAD

**Issue by XVilka** [williballenthin/python-idb#88]
Running on https://github.com/williballenthin/python-idb/blob/master/tests/data/v6.8/x32/kernel32.idb it returns the following error:
```
[i] ℤ python3 dump_user.py ../tests/data/v6.8/x32/kernel32.idb                                                                                                                                                                     12:50:10 
WARNING:idb.fileformat:section class not implemented: id2
INFO:idb.netnode:resolved string netnode $ structs to ff000027
INFO:idb.netnode:resolved string netnode $ original user to ff00003c
Traceback (most recent call last):
  File "dump_user.py", line 139, in <module>
    sys.exit(main())
  File "dump_user.py", line 128, in main
    data = get_userdata(api.ida_netnode.netnode("$ original user"))
  File "dump_user.py", line 97, in get_userdata
    return parse_user_data(userdata)
  File "dump_user.py", line 69, in parse_user_data
    name = buf[0x23 : buf.find(b"\x00", 0x23)].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1-2: invalid continuation byte
```

Curiously, it works without any issue for 6.7 version IDB: `tests/data/v6.7/x32/kernel32.idb`

**Comment by XVilka** [comment]
Fixed in https://github.com/williballenthin/python-idb/commit/0e2c5459b0b1245e0c1a29f009205826eead1fbf
